params = {
    "3DS 2.0 Hourly Data (2)": {"changepoint_prior_scale": 10,
                "changepoint_range": 0.731476707,
                "seasonality_prior_scale": 6.436092063,
                "daily_prior": 2,
                "yearly_prior": 2,
                "weekly_prior": -2,
                "fourier_order_daily": 2, 
                "fourier_order_yearly" : 5, 
                "fourier_order_weekly": 2},
    "CGK1 Hourly Data": {"changepoint_prior_scale": 10,
                "changepoint_range": 0.730358052,
                "seasonality_prior_scale": 1,
                "daily_prior": -2,
                "yearly_prior": 2, 
                "weekly_prior": 2,
                "fourier_order_daily": 5,
                "fourier_order_yearly" : 5, 
                "fourier_order_weekly": 5},
}
